### ISSUE TITLE
create a searchable subfield for commonly swapped characters

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/catalogue-api#635] opened 2023-03-21 09:52 UTC
[original thread here](https://wellcome.slack.com/archives/C8X9YKM5X/p1679309592820029)

**Comment by jtweed** [comment] 2023-03-29 12:49
Dupe of https://github.com/wellcomecollection/platform/issues/5672

**Closed by jtweed** 2023-03-29 12:49 UTC
Labels: search relevance
